hp_fir_filter = designfilt('highpassfir', ...
    'FilterOrder',125, ...
    'CutoffFrequency',0.5,...    
    'SampleRate',200);

fvtool(hp_fir_filter);



hp_iir_filter = designfilt('highpassiir', ...
         'FilterOrder',2, ...
         'HalfPowerFrequency',0.5, ...
         'DesignMethod','butter', ...
         'SampleRate',200);
fvtool(hp_iir_filter);